export default {
  books: [
    {
      title: "Physics1",
      asset: require("../assets/images/books/12/Physics_Part1-Physics1-12.jpg"),
      subject: "Physics Part1",
      class: "12",
    },
    {
      title: "Business Studies1",
      asset: require("../assets/images/books/12/Business_Studies_Part1-Business_Studies1-12.jpg"),
      subject: "Business Studies Part1",
      class: "12",
    },
    {
      title: "Hindi Core",
      asset: require("../assets/images/books/12/Vitan_2-Hindi_Core-12.jpg"),
      subject: "Vitan 2",
      class: "12",
    },
    {
      title: "Sanskrit",
      asset: require("../assets/images/books/12/Shasvati_2-Sanskrit-12.jpg"),
      subject: "Shasvati 2",
      class: "12",
    },
    {
      title: "English Supplementary Reader",
      asset: require("../assets/images/books/12/Vistas-English_Supplementary_Reader-12.jpg"),
      subject: "Vistas",
      class: "12",
    },
    {
      title: "Chemistry1",
      asset: require("../assets/images/books/12/Chemistry_Part1-Chemistry1-12.jpg"),
      subject: "Chemistry Part1",
      class: "12",
    },
    {
      title: "Sociology1",
      asset: require("../assets/images/books/12/Indian_Society-Sociology1-12.jpg"),
      subject: "Indian Society",
      class: "12",
    },
    {
      title: "Sanskrit",
      asset: require("../assets/images/books/12/Bhasvati_2-Sanskrit-12.jpg"),
      subject: "Bhasvati 2",
      class: "12",
    },
    {
      title: "Mathematics1",
      asset: require("../assets/images/books/12/Mathematics_Part1-Mathematics1-12.jpg"),
      subject: "Mathematics Part1",
      class: "12",
    },
    {
      title: "Business Studies2",
      asset: require("../assets/images/books/12/Business_Studies_Part2-Business_Studies2-12.jpg"),
      subject: "Business Studies Part2",
      class: "12",
    },
    {
      title: "Hindi",
      asset: require("../assets/images/books/7-8/Durva-Hindi-8.jpg"),
      subject: "Durva",
      class: "8",
    },
    {
      title: "English",
      asset: require("../assets/images/books/7-8/HoneyDew-English-8.jpg"),
      subject: "HoneyDew",
      class: "8",
    },
    {
      title: "Social Science",
      asset: require("../assets/images/books/7-8/Social and Political Life III-Social Science-8.jpg"),
      subject: "Social and Political Life III",
      class: "8",
    },
    {
      title: "Mathematics",
      asset: require("../assets/images/books/7-8/Mathematics-Mathematics-8.jpg"),
      subject: "Mathematics",
      class: "8",
    },
    {
      title: "Social Science",
      asset: require("../assets/images/books/7-8/Our Environment-Social Science-7.jpg"),
      subject: "Our Environment",
      class: "7",
    },
    {
      title: "Urdu",
      asset: require("../assets/images/books/7-8/Urdu Guldusta-Urdu-7.jpg"),
      subject: "Urdu Guldusta",
      class: "7",
    },
    {
      title: "Urdu",
      asset: require("../assets/images/books/7-8/Door Paas-Urdu-7.jpg"),
      subject: "Door Paas",
      class: "7",
    },
    {
      title: "Hindi",
      asset: require("../assets/images/books/7-8/Vasant-Hindi-7.jpg"),
      subject: "Vasant",
      class: "7",
    },
    {
      title: "Sanskrit",
      asset: require("../assets/images/books/7-8/Ruchira-Sanskrit-8.jpg"),
      subject: "Ruchira",
      class: "8",
    },
    {
      title: "Hindi",
      asset: require("../assets/images/books/7-8/Durva-Hindi-7.jpg"),
      subject: "Durva",
      class: "7",
    },
    {
      title: "Geography",
      asset: require("../assets/images/books/7-8/Social Science Resources and Development-Geography-8.jpg"),
      subject: "Social Science Resources and Development",
      class: "8",
    },
    {
      title: "Urdu",
      asset: require("../assets/images/books/7-8/Apni Zaban-Urdu-7.png"),
      subject: "Apni Zaban",
      class: "7",
    },
    {
      title: "English Supplementary Reader",
      asset: require("../assets/images/books/7-8/An Alien Hand-English_Supplementary_Reader-7.jpg"),
      subject: "An Alien Hand",
      class: "7",
    },
    {
      title: "Mathematics",
      asset: require("../assets/images/books/7-8/Mathematics-Mathematics-7.jpg"),
      subject: "Mathematics",
      class: "7",
    },
    {
      title: "Science",
      asset: require("../assets/images/books/7-8/Science-Science-7.jpg"),
      subject: "Science",
      class: "7",
    },
    {
      title: "Social Science",
      asset: require("../assets/images/books/7-8/Social and Political Life II-Social Science-7.jpg"),
      subject: "Social and Political Life II",
      class: "7",
    },
    {
      title: "Hindi",
      asset: require("../assets/images/books/7-8/Vasant-Hindi-8.jpg"),
      subject: "Vasant",
      class: "8",
    },
    {
      title: "Science",
      asset: require("../assets/images/books/7-8/Science-Science-8.jpg"),
      subject: "Science",
      class: "8",
    },
    {
      title: "biology",
      asset: require("../assets/images/books/11/Biology-biology-11.jpg"),
      subject: "Biology",
      class: "11",
    },
    {
      title: "Political Science",
      asset: require("../assets/images/books/11/Indian_Constitution_at_Work-Political_Science-11.jpg"),
      subject: "Indian Constitution at Work",
      class: "11",
    },
    {
      title: "history",
      asset: require("../assets/images/books/11/Themes_in_world_history-history-11.jpg"),
      subject: "Themes in world history",
      class: "11",
    },
    {
      title: "Accountancy",
      asset: require("../assets/images/books/11/Accountancy_Part_II-Accountancy-11.jpg"),
      subject: "Accountancy Part II",
      class: "11",
    },
    {
      title: "economics",
      asset: require("../assets/images/books/11/Statistics_for_economics-economics-11.jpg"),
      subject: "Statistics for economics",
      class: "11",
    },
    {
      title: "hindi",
      asset: require("../assets/images/books/11/Vitran_Part_1-hindi-11.jpg"),
      subject: "Vitran Part 1",
      class: "11",
    },
    {
      title: "Physics",
      asset: require("../assets/images/books/11/Physics_Part_I-Physics-11.jpg"),
      subject: "Physics Part I",
      class: "11",
    },
    {
      title: "Accountancy",
      asset: require("../assets/images/books/11/Accountancy_Part_I-Accountancy-11.jpg"),
      subject: "Accountancy Part I",
      class: "11",
    },
    {
      title: "Chemistry",
      asset: require("../assets/images/books/11/Chemistry_Part_II-Chemistry-11.jpg"),
      subject: "Chemistry Part II",
      class: "11",
    },
    {
      title: "Physics",
      asset: require("../assets/images/books/11/Physics_Part_II-Physics-11.jpg"),
      subject: "Physics Part II",
      class: "11",
    },
    {
      title: "business studies",
      asset: require("../assets/images/books/11/Business_Studies-business_studies-11.jpg"),
      subject: "Business Studies",
      class: "11",
    },
    {
      title: "English",
      asset: require("../assets/images/books/11/Hornbill-English-11.jpg"),
      subject: "Hornbill",
      class: "11",
    },
    {
      title: "Mathematics",
      asset: require("../assets/images/books/11/Mathematics-Mathematics-11.jpg"),
      subject: "Mathematics",
      class: "11",
    },
    {
      title: "Political Science",
      asset: require("../assets/images/books/11/Political_Theory-Political_Science-11.jpg"),
      subject: "Political Theory",
      class: "11",
    },
    {
      title: "hindi",
      asset: require("../assets/images/books/11/Aroha_Part_2-hindi-11.jpg"),
      subject: "Aroha Part 2",
      class: "11",
    },
    {
      title: "hindi",
      asset: require("../assets/images/books/11/Anthral-hindi-11.jpg"),
      subject: "Anthral",
      class: "11",
    },
    {
      title: "Chemistry",
      asset: require("../assets/images/books/11/Chemistry_Part_I-Chemistry-11.jpg"),
      subject: "Chemistry Part I",
      class: "11",
    },
  ],
};
